#!/bin/bash

# Startup options
ROPTIONS="--vanilla --quiet"
SCRIPTNAME=plot_model2.R

echo "Starting VStar plotter...";
cd "$( dirname "${BASH_SOURCE[0]}" )"
echo "Current directory: $PWD"


if [ ! -f $SCRIPTNAME ]
then
	echo "**** ERROR: Cannot find $SCRIPTNAME"
	exit 1
fi

Rscript $ROPTIONS -e "source('$SCRIPTNAME')"
